Fix dashboard publishing when the project name is computed
Pull request #2055 (fix(Reporting): Fix issue with relative paths that miss the root folder) broke pull request #1710 (fix: Dashboard baseline project name and version are not set).

I have added a new test to ensure that this does not regress in the future.

Before this commit, an HTTP 404 error would occur because the dashboard URL was not correct:

```
[12:46:37 ERR] Failed to upload report to the dashboard
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Stryker.Core.Clients.DashboardClient.PublishReport(JsonReport report, String version)
[12:46:37 ERR] Uploading to stryker dashboard failed...
```