fix(rollback): Improve rollback for CS0165 and CS0177 compile errors  (#3548)
* feat: improve rollback logic for error CS0165

* feat: rollbacks mutation erasing assignment on CS0165

* chore: Sonar

* misc: copilot warnings

* test: adjust expected scoring

* misc: minor fixes

* misc: sonar fixes

* chore: copilot comments

* chore: mino redesign

* misc: copilot

* feat: add specific logic for missing returns (WIP)

* misc: refine rollback logic

* fix: sonar issues

* chore: code clean up

* chore: comestic fixes

* core: copilot remarks

* misc: adjust rety logic when Roslyn compiler crashes

* chore: copilot comments

* test: mix RollbackProcess_ShouldRollbackMutationsErasingAssignment

* misc: improve assignment detection

* chore: improve detection for assignment

* chore: cleanup assignment detection

---------

Co-authored-by: Rouke Broersma <mobrockers@gmail.com>